#!/bin/bash

#JAVA_HOME="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"
#JAVA_BIN="${JAVA_HOME}/bin/java"
JAVA_BIN=java

WEAVE_BINPATH=$(dirname $0)
WEAVE_CLASSPATH="${WEAVE_BINPATH}/target/classes:${WEAVE_BINPATH}/libs/*:${WEAVE_BINPATH}/runtime-libs/*" 

#echo "${JAVA_BIN} -cp $WEAVE_CLASSPATH org.exfio.weave.client.WeaveClientCLI $@"
"${JAVA_BIN}" -cp $WEAVE_CLASSPATH org.exfio.weave.client.WeaveClientCLI "$@"
