#!/bin/bash

BINDIR="$(dirname $0)"

#echo "mvn -e -f $BINDIR/pom.xml -q exec:java -Dexec.mainClass=org.exfio.weave.account.WeaveAccountCLI -Dexec.args=$*"
mvn -e -f "$BINDIR/pom.xml" -q exec:java -Dexec.mainClass=org.exfio.weave.account.WeaveAccountCLI -Dexec.args="$*"
