#!/bin/bash

BINDIR="$(dirname $0)"

#echo "mvn -f $BINDIR/pom.xml -q exec:java -Dexec.mainClass=org.exfio.weave.client.WeaveClientCLI -Dexec.args=$*"
mvn -f "$BINDIR/pom.xml" -q exec:java -Dexec.mainClass=org.exfio.weave.client.WeaveClientCLI -Dexec.args="$*"
